const questions = [
  { question: "Yksi", playersNeeded: 1 },
  { question: "Yksi", playersNeeded: 1 },
  { question: "Yksi", playersNeeded: 1 },
  { question: "Yksi", playersNeeded: 1 },
  { question: "Kaikki", playersNeeded: 0 },
  { question: "Yksi", playersNeeded: 1 },
  { question: "Kaksi", playersNeeded: 2 },
  { question: "Kaksi", playersNeeded: 2 },
  { question: "Kaksi", playersNeeded: 2 },
  { question: "Kaikki", playersNeeded: 0 },
  { question: "Juo Kolme hKaikki", playersNeeded: 0 },
  { question: "Juo Kolme hKaikki", playersNeeded: 0 },
  { question: "Juo Viisi hKaikki", playersNeeded: 0 },
  { question: "Juo Kuusi hKaikki", playersNeeded: 0 },
  { question: "Kaikki", playersNeeded: 0 },
  { question: "Yksi", playersNeeded: 1 },
  { question: "Kaksi", playersNeeded: 2 },
  { question: "Kaksi", playersNeeded: 2 },
  { question: "Kaksi", playersNeeded: 2 },
  { question: "Kaikki", playersNeeded: 0 },
  { question: "Yksi", playersNeeded: 1 },
  { question: "Kaksi", playersNeeded: 2 },
  { question: "Kaksi", playersNeeded: 2 },
  { question: "Yksi", playersNeeded: 1 },
  { question: "Kaikki", playersNeeded: 0 },
];

export default questions;
