const questions = [
  {
    gamemode: "BaseGame",
    question: "Jos olet sinkku juo kolme huikkaa",
    playersNeeded: 0,
  },
  {
    gamemode: "ColorGame",
    question: "None",
    playersNeeded: 1,
  },
  {
    gamemode: "ColorGame",
    question: "None",
    playersNeeded: 1,
  },
  {
    gamemode: "ColorGame",
    question: "None",
    playersNeeded: 1,
  },
  {
    gamemode: "ColorGame",
    question: "None",
    playersNeeded: 1,
  },
  {
    gamemode: "ColorGame",
    question: "None",
    playersNeeded: 1,
  },
  {
    gamemode: "ColorGame",
    question: "None",
    playersNeeded: 1,
  },
  {
    gamemode: "ColorGame",
    question: "None",
    playersNeeded: 1,
  },
  {
    gamemode: "BaseGame",
    question: "Vanhin pelaaja juo kaksi huikkaa",
    playersNeeded: 0,
  },
  {
    gamemode: "BaseGame",
    question: "Nuorin pelaaja juo kolme huikkaa",
    playersNeeded: 0,
  },
  {
    gamemode: "BaseGame",
    question: "Jos olet syntynyt 2000-luvulla, juo kolme huikkaa",
    playersNeeded: 0,
  },
  {
    gamemode: "BaseGame",
    question: "Vanhin pelaaja juo kaksi huikkaa",
    playersNeeded: 0,
  },
  {
    gamemode: "BaseGame",
    question: "Nuorin pelaaja juo kolme huikkaa",
    playersNeeded: 0,
  },
  { gamemode: "BaseGame", question: "Kaikki juo vettä", playersNeeded: 0 },
  { gamemode: "BaseGame", question: "Juo yksi huikka", playersNeeded: 1 },
  { gamemode: "BaseGame", question: "Anna kaksi huikkaa", playersNeeded: 1 },
  { gamemode: "BaseGame", question: "Kategoriat", playersNeeded: 1 },
  { gamemode: "BaseGame", question: "Anna viisi huikkaa", playersNeeded: 1 },
  {
    gamemode: "BaseGame",
    question: "Kaikki juovat kaksi huikkaa",
    playersNeeded: 0,
  },
  { gamemode: "BaseGame", question: "Keksi sääntö", playersNeeded: 1 },
  {
    gamemode: "BaseGame",
    question: "Pelatkaa kivi-sakset-paperi, häviäjä juo kolme huikkaa",
    playersNeeded: 2,
  },
  {
    gamemode: "BaseGame",
    question: "Pelatkaa kivi-sakset-paperi, voittaja saa antaa neljä huikkaa",
    playersNeeded: 2,
  },
  {
    gamemode: "BaseGame",
    question: "Teistä lyhyemmämpi saa antaa kaksi huikkaa",
    playersNeeded: 2,
  },
  {
    gamemode: "BaseGame",
    question: "Jos olet parisuhteessa juo kolme huikkaa",
    playersNeeded: 0,
  },

  { gamemode: "BaseGame", question: "Kategoriat", playersNeeded: 1 },
  { gamemode: "BaseGame", question: "Vesiputous", playersNeeded: 1 },
  { gamemode: "BaseGame", question: "Äänestys, keksi aihe", playersNeeded: 1 },
  { gamemode: "BaseGame", question: "Anna kuusi huikkaa", playersNeeded: 1 },
  { gamemode: "BaseGame", question: "Anna neljä huikkaa", playersNeeded: 1 },
  { gamemode: "BaseGame", question: "Never have I ever", playersNeeded: 1 },
  { gamemode: "BaseGame", question: "Totuus vai Tehtävä?", playersNeeded: 1 },
  { gamemode: "BaseGame", question: "Totuus vai Tehtävä?", playersNeeded: 1 },
  { gamemode: "BaseGame", question: "Juo kolme huikkaa", playersNeeded: 1 },
  { gamemode: "BaseGame", question: "Juo viisi huikkaa", playersNeeded: 1 },
  { gamemode: "BaseGame", question: "Juo kolme huikkaa", playersNeeded: 1 },
  { gamemode: "BaseGame", question: "Juo viisi huikkaa", playersNeeded: 1 },
  {
    gamemode: "BaseGame",
    question: `Jos et asu helsingissä,
  juo kaksi huikkaa`,
    playersNeeded: 0,
  },
  { gamemode: "BaseGame", question: "Anna kaksi huikkaa", playersNeeded: 1 },
  { gamemode: "BaseGame", question: "Anna kuusi huikkaa", playersNeeded: 1 },
  { gamemode: "BaseGame", question: "Anna kuusi huikkaa", playersNeeded: 1 },
  { gamemode: "BaseGame", question: "Anna neljä huikkaa", playersNeeded: 1 },
  { gamemode: "BaseGame", question: "Anna kuusi huikkaa", playersNeeded: 1 },
  { gamemode: "BaseGame", question: "Anna neljä huikkaa", playersNeeded: 1 },
  { gamemode: "BaseGame", question: "Keksi sääntö", playersNeeded: 1 },
  {
    gamemode: "BaseGame",
    question: "Pelatkaa kivi-sakset-paperi, häviäjä juo kolme huikkaa",
    playersNeeded: 2,
  },
  {
    gamemode: "ColorGame",
    question: "None",
    playersNeeded: 1,
  },
  {
    gamemode: "ColorGame",
    question: "None",
    playersNeeded: 1,
  },
  {
    gamemode: "ColorGame",
    question: "None",
    playersNeeded: 1,
  },
];

export default questions;
