const questions = [
  { question: "Juo yksi huikka", playersNeeded: 1 },
  { question: "Anna kaksi huikkaa", playersNeeded: 1 },
  { question: "Kategoriat", playersNeeded: 1 },
  { question: "Anna viisi huikkaa", playersNeeded: 1 },
  { question: "Kaikki juovat kaksi huikkaa", playersNeeded: 0 },
  { question: "Keksi sääntö", playersNeeded: 1 },
  {
    question: "Pelatkaa kivi-sakset-paperi, häviäjä juo kolme huikkaa",
    playersNeeded: 2,
  },
  {
    question: "Pelatkaa kivi-sakset-paperi, voittaja saa antaa neljä huikkaa",
    playersNeeded: 2,
  },
  { question: "Teistä lyhyemmämpi saa antaa kaksi huikkaa", playersNeeded: 2 },
  { question: "Jos olet parisuhteessa juo kolme huikkaa", playersNeeded: 0 },
  { question: "Jos olet sinkku juo kolme huikkaa", playersNeeded: 0 },
  { question: "Vanhin pelaaja juo kaksi huikkaa", playersNeeded: 0 },
  { question: "Nuorin pelaaja juo kolme huikkaa", playersNeeded: 0 },
  {
    question: "Jos olet syntynyt 200-luvulla, juo kolme huikkaa",
    playersNeeded: 0,
  },
  { question: "Kaikki juo vettä", playersNeeded: 0 },
  { question: "Kategoriat", playersNeeded: 1 },
  { question: "Vesiputous", playersNeeded: 1 },
  { question: "Äänestys, keksi aihe", playersNeeded: 1 },
  { question: "Anna kuusi huikkaa", playersNeeded: 1 },
  { question: "Anna neljä huikkaa", playersNeeded: 1 },
  { question: "Never have I ever", playersNeeded: 1 },
  { question: "Totuus vai Tehtävä?", playersNeeded: 1 },
  { question: "Totuus vai Tehtävä?", playersNeeded: 1 },
  { question: "Juo kolme huikkaa", playersNeeded: 1 },
  { question: "Juo viisi huikkaa", playersNeeded: 1 },
  { question: "Juo kolme huikkaa", playersNeeded: 1 },
  { question: "Juo viisi huikkaa", playersNeeded: 1 },
  {
    question: `Jos et asu helsingissä,
  juo kaksi huikkaa`,
    playersNeeded: 0,
  },
  { question: "Anna kaksi huikkaa", playersNeeded: 1 },
  { question: "Anna kuusi huikkaa", playersNeeded: 1 },
];

export default questions;
